const {test}=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs'),path=require('node:path');
const ROOT=path.join(__dirname,'../vault');
const BASE='06 Sports Betting/Football/CFB';
const engine=new Function(fs.readFileSync(path.join(ROOT,BASE,'Views/cfb-engine.js'),'utf8'))();
const viewSource=fs.readFileSync(path.join(ROOT,BASE,'Views/cfb-team.js'),'utf8');
const AsyncFunction=Object.getPrototypeOf(async function(){}).constructor;
// Obsidian supplies a full YAML parser in production. This adapter only handles
// the scalar/list subset generated by these templates, and leaves custom blocks opaque.
function parseYaml(text){
  const out={};
  for(const line of text.split('\n')){
    const m=line.match(/^([a-z_]+):\s*(.*)$/);if(!m)continue;
    let value=m[2];try{value=JSON.parse(value)}catch{if(!value)value=null;}
    out[m[1]]=value;
  }return out;
}
const metadata=text=>parseYaml(text.match(/^---\n([\s\S]*?)\n---/)[1]);
const paths={home:`${BASE}/Teams/Home U.md`,away:`${BASE}/Teams/Away U.md`};
function fixture(){return {
  game:{game_id:123,home_team_id:1,away_team_id:2,home_team:'Home U',away_team:'Away U',season:2099,week:6,
    start_date:'2099-10-10T01:00:00Z',neutral_site:0,completed:0,venue:'Home Stadium',home_conference:'A',away_conference:'B',
    advanced_metrics:{'Home U':{offense_success_rate:.45,defense_ppa:-.12,season:2099}}},
  preview:{projection:{as_of_date:'2099-10-08',home:{drives:12,plays:60,expected_points:24},away:{expected_points:21},
    home_snapshot:{games:4,seconds_per_play:25,seconds_per_play_allowed:27},points_model:{model_version:'v2'}}},
  situation:{game_id:123,lines:{providers:[{provider:'DraftKings',spread:-3.5,over_under:48.5,home_moneyline:-180,away_moneyline:150,
    spread_open:-1.5,over_under_open:50.5,fetched_at:'2099-10-08T00:00:00Z'}]},
    weather:{available:true,latest:{temperature:60,sustained_wind:15,wind_gust:20,condition:'Clear',precipitation_probability:5,
      forecast_generated_at:'2099-10-08',source:'open-meteo'}},travel:{detail:'Away U travels 500 miles'},
    schedule_spots:[{type:'REST',team:'Home U',headline:'Off a bye',detail:'14 days of rest'}],
    availability:[{content_id:10,school:'Away U',title:'Quarterback questionable',source_role:'REPORTING',published_at:'2099-10-08',canonical_url:'https://news.test/a',publisher_name:'Reporter'}]},
  content:{reported:[{content_id:11,title:'Matchup report',published_at:'2099-10-08',canonical_url:'https://news.test/b',source_role:'REPORTING'}]},errors:[]};}
function initial(p=fixture()){return engine.emptyNote(p.game,paths,'2099-10-09');}
function refresh(text,p=fixture()){return engine.refresh(text,p,p.situation?.lines?.providers[0]??null,paths,'2099-10-08T12:00:00Z','https://engine.test',parseYaml,'America/New_York');}

test('initial import maps real API fields, home signs, forecast units, and blank juice',()=>{
  const text=refresh(initial()),fm=metadata(text);
  assert.equal(fm.line,-3.5);assert.equal(fm.total,48.5);assert.equal(fm.price,null);
  assert.equal(fm.over_price,null);assert.equal(fm.engine_game_id,123);assert.equal(fm.home_moneyline,-180);
  assert(text.includes('45.0%'));assert(text.includes('60 °F'));assert(text.includes('15 mph wind'));
  assert(text.includes('| Home U | 12 | 60 | 24 |'));assert(text.includes('Seconds / play allowed: 27.00'));
  assert(text.includes('Quarterback questionable. Role: REPORTING'));assert(!text.includes('confirmed out'));
});
test('refresh preserves every manual section, initial quote, and custom multiline properties',()=>{
  let text=refresh(initial());text=text.replace('- Thesis:','- Thesis: MY ORIGINAL CONCLUSION')
    .replace('line: -3.5','line: -4').replace('status: "research"','status: "bet"')
    .replace('---\n','---\ncustom: |\n  multi\n  line\n');
  const p=fixture();p.situation.lines.providers[0].spread=-6;
  const next=refresh(text,p),fm=metadata(next);
  assert.equal(fm.line,-4);assert.equal(fm.engine_line,-6);assert.equal(fm.status,'bet');
  assert(next.includes('MY ORIGINAL CONCLUSION'));assert(next.includes('custom: |\n  multi\n  line'));
  assert(next.includes('<!-- cfb:home-offense:start -->\n| + | - |'));
});
test('no quote from a different book fills initial fields under the original book',()=>{
  const text=initial().replace('sportsbook: ""','sportsbook: "Bovada"');
  const fm=metadata(refresh(text));assert.equal(fm.line,null);assert.equal(fm.total,null);
  assert.equal(fm.sportsbook,'Bovada');assert.equal(fm.engine_sportsbook,'DraftKings');
});
test('observations deduplicate by stable ID and retain user directions and lifecycle edits',()=>{
  let text=refresh(initial());text=text.replace('|  |  | Quarterback questionable.', '| Important absence |  | Quarterback questionable.')
    .replace('| watch | 2099-10-09 | availability:away:10 |','| retired | when starter returns | availability:away:10 |');
  const next=refresh(text);
  assert.equal((next.match(/availability:away:10/g)||[]).length,1);
  assert(/\| Important absence \| *\| Quarterback questionable\./.test(next));
  assert(next.includes('| retired | when starter returns | availability:away:10 |'));
});
test('older reporting and availability stay linked when absent from latest response',()=>{
  const p=fixture(),old=refresh(initial());p.content={};p.situation.availability=[];
  const next=refresh(old,p);assert(next.includes('https://news.test/a'));assert(next.includes('https://news.test/b'));
});
test('partial endpoint failure retains previous weather, reporting, projection, and latest quote',()=>{
  const old=refresh(initial()),p=fixture();delete p.situation;delete p.preview;delete p.content;p.errors=['situation unavailable'];
  const next=refresh(old,p),fm=metadata(next);assert(next.includes('15 mph wind'));assert(next.includes('Matchup report'));
  assert(next.includes('| Home U | 12 | 60 | 24 |'));assert.equal(fm.engine_line,-3.5);assert.equal(fm.engine_import_status,'partial');
});
test('missing market/forecast remain unknown and zero is preserved',()=>{
  const p=fixture();p.situation.lines.providers[0].spread=0;p.situation.weather={available:false};
  let next=refresh(initial(p),p);assert.equal(metadata(next).line,0);assert(next.includes('no forecast available'));
  p.situation.lines.providers=[];next=refresh(next,p);assert.equal(metadata(next).engine_line,null);
  assert(next.includes('no selected provider quote'));assert(!next.includes('consensus_spread'));
});
test('neutral games omit incorrect home-campus travel and kickoff date uses local timezone',()=>{
  const p=fixture();p.game.neutral_site=1;const next=refresh(initial(p),p);
  assert(!next.includes('Away U travels 500 miles'));assert(next.includes('Neutral site'));
  assert.equal(engine.dateInZone('2099-10-10T01:00:00Z'),'2099-10-09');
});
test('URLs and identity conflicts stop rather than sending notes or merging the wrong game',()=>{
  assert.equal(engine.parseGameInput('https://engine.test/college-football/games/123/','https://engine.test'),123);
  assert.throws(()=>engine.parseGameInput('https://other.test/college-football/games/123/','https://engine.test'),/different engine/);
  assert.throws(()=>engine.baseUrl('http://external.test'),/HTTPS/);assert.equal(engine.baseUrl('http://localhost:5000'),'http://localhost:5000');
  assert.throws(()=>refresh(initial().replace('season: 2099','season: 2098')),/season/);
  assert.throws(()=>refresh(initial().replace('Home U.md','Other U.md').replace('Teams/Home U]]','Teams/Other U]]')),/home team/);
  assert.throws(()=>refresh(refresh(initial()).replace('engine_game_id: 123','engine_game_id: 999')),/another engine game/);
});
test('damaged marker refuses refresh and retrospective data are identified',()=>{
  assert.throws(()=>refresh(refresh(initial()).replace('<!-- cfb:engine-home-offense:end -->','')),/Damaged/);
  const p=fixture();p.game.completed=1;assert(refresh(initial(p),p).includes('Retrospective import'));
});
function runtime(p=fixture()){
  const files=new Map([[`${BASE}/Views/team-page.md`,fs.readFileSync(path.join(ROOT,BASE,'Views/team-page.md'),'utf8')]]);
  const file=p=>files.has(p)?{path:p,basename:p.split('/').at(-1).replace(/\.md$/,'')}:null;
  const prompts=['123','123'];const hooks=[];
  const tp={file:{path:()=>`${BASE}/CFB Dashboard.md`},hooks:{on_all_templates_executed:fn=>hooks.push(fn)},
    system:{prompt:async()=>prompts.shift(),suggester:async(labels,values)=>values[0]},
    obsidian:{parseYaml,Notice:class {},requestUrl:async({url,method})=>{
      assert.equal(method,'GET');const kind=url.split('/').at(-1);
      return {status:200,json:kind==='123'?p.game:kind==='preview'?p.preview:kind==='situation'?p.situation:p.content};}},
    app:{workspace:{openLinkText:()=>{}},vault:{getAbstractFileByPath:file,getMarkdownFiles:()=>[...files.keys()].filter(p=>p.endsWith('.md')).map(file),
      read:async f=>files.get(f.path),createFolder:async p=>files.set(p,null),create:async(p,text)=>{assert(!files.has(p));files.set(p,text);return file(p)},
      process:async(f,fn)=>files.set(f.path,fn(files.get(f.path)))}}};return {tp,files};
}
test('end-to-end Templater run creates/reuses team pages and refreshes one matchup',async()=>{
  const {tp,files}=runtime();const first=await engine.run(tp);assert.equal(metadata(files.get(first)).engine_game_id,123);
  assert.equal([...files.keys()].filter(p=>p.startsWith(`${BASE}/Teams/`)&&p.endsWith('.md')).length,2);
  files.set(first,files.get(first).replace('- Thesis:','- Thesis: KEEP'));
  const second=await engine.run(tp);assert.equal(second,first);assert(files.get(first).includes('- Thesis: KEEP'));
  const snap=await engine.freeze(tp);assert.equal(metadata(files.get(snap)).type,'cfb-pregame-snapshot');
  assert(files.get(snap).includes('- Thesis: KEEP'));assert.equal(metadata(files.get(first)).type,'cfb-matchup');
});
test('snapshot after kickoff and import from active matchup are refused',async()=>{
  const p=fixture();p.game.start_date='2020-10-10T16:00:00Z';const {tp,files}=runtime(p);await engine.run(tp);
  await assert.rejects(engine.freeze(tp),/Kickoff has passed/);
  tp.file.path=()=>`${BASE}/Matchups/active.md`;await assert.rejects(engine.run(tp),/CFB Dashboard/);
});
test('required game failure writes no notes',async()=>{
  const {tp,files}=runtime();tp.obsidian.requestUrl=async()=>({status:503,json:{}});
  await assert.rejects(engine.run(tp),/HTTP 503/);assert.equal(files.size,1);
});
test('unrelated index notes in team/matchup folders do not block import or snapshot',async()=>{
  const {tp,files}=runtime();files.set(`${BASE}/Teams/Index.md`,'# Teams index');
  files.set(`${BASE}/Matchups/Index.md`,'# Matchups index');
  const target=await engine.run(tp);assert.equal(metadata(files.get(target)).type,'cfb-matchup');
  const snapshot=await engine.freeze(tp);assert.equal(metadata(files.get(snapshot)).type,'cfb-pregame-snapshot');
});
test('team queries include neutral imported evidence, isolate side, and show opponent/context',async()=>{
  const text=refresh(initial());const output=[];const dv={
    current:()=>({file:{path:paths.home},season:2099}),
    pages:()=>[{...metadata(text),file:{path:`${BASE}/Matchups/game.md`}}],
    io:{load:async()=>text},date:()=>({toFormat:()=> '2099-10-08'}),
    fileLink:(path,e,label)=>({path,label,toString:()=>`[[${path}]]`}),sectionLink:(path,section,e,label)=>({path,section,label}),
    table:(headers,rows)=>output.push({headers,rows}),paragraph:text=>output.push({text}),header:(level,text)=>output.push({text})};
  await new AsyncFunction('dv','input',viewSource)(dv,{mode:'offense'});
  assert(output[0].rows.length>0);assert.equal(output[0].rows[0][1],metadata(text).away_team);
  assert(output[0].rows.some(row=>String(row[5]).includes('45.0%')));assert(!JSON.stringify(output).includes('Quarterback questionable'));
  output.length=0;await new AsyncFunction('dv','input',viewSource)(dv,{mode:'games'});
  assert(JSON.stringify(output).includes('Matchup report'));assert(JSON.stringify(output).includes('15 mph wind'));
});
