const {test}=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs'),path=require('node:path');
const ROOT=path.join(__dirname,'../vault');
const BASE='06 Sports Betting/Football/CFB';
const engine=new Function(fs.readFileSync(path.join(ROOT,BASE,'Views/cfb-engine.js'),'utf8'))();
const viewSource=fs.readFileSync(path.join(ROOT,BASE,'Views/cfb-team.js'),'utf8');
const AsyncFunction=Object.getPrototypeOf(async function(){}).constructor;
// Obsidian supplies a full YAML parser in production. This adapter only handles
// the scalar/list subset generated by these templates, and leaves custom blocks opaque.
function parseYaml(text){
  const out={};
  for(const line of text.split('\n')){
    const m=line.match(/^([a-z_]+):\s*(.*)$/);if(!m)continue;
    let value=m[2];try{value=JSON.parse(value)}catch{if(!value)value=null;}
    out[m[1]]=value;
  }return out;
}
const metadata=text=>parseYaml(text.match(/^---\n([\s\S]*?)\n---/)[1]);
const paths={home:`${BASE}/Teams/Home U.md`,away:`${BASE}/Teams/Away U.md`};
function fixture(){return {
  game:{game_id:123,home_team_id:1,away_team_id:2,home_team:'Home U',away_team:'Away U',season:2099,week:6,
    start_date:'2099-10-10T01:00:00Z',neutral_site:0,completed:0,venue:'Home Stadium',home_conference:'A',away_conference:'B',
    advanced_metrics:{'Home U':{offense_success_rate:.45,defense_ppa:-.12,season:2099}}},
  preview:{projection:{as_of_date:'2099-10-08',home:{drives:12,plays:60,expected_points:24},away:{expected_points:21},
    home_snapshot:{games:4,seconds_per_play:25,seconds_per_play_allowed:27},points_model:{model_version:'v2'}}},
  situation:{game_id:123,lines:{providers:[{provider:'DraftKings',spread:-3.5,over_under:48.5,home_moneyline:-180,away_moneyline:150,
    spread_open:-1.5,over_under_open:50.5,fetched_at:'2099-10-08T00:00:00Z'}]},
    weather:{available:true,latest:{temperature:60,sustained_wind:15,wind_gust:20,condition:'Clear',precipitation_probability:5,
      forecast_generated_at:'2099-10-08',source:'open-meteo'}},travel:{detail:'Away U travels 500 miles'},
    schedule_spots:[{type:'REST',team:'Home U',headline:'Off a bye',detail:'14 days of rest'}],
    availability:[{content_id:10,school:'Away U',title:'Quarterback questionable',source_role:'REPORTING',published_at:'2099-10-08',canonical_url:'https://news.test/a',publisher_name:'Reporter'}]},
  content:{reported:[{content_id:11,title:'Matchup report',published_at:'2099-10-08',canonical_url:'https://news.test/b',source_role:'REPORTING'}]},errors:[]};}
function initial(p=fixture()){return engine.emptyNote(p.game,paths,'2099-10-09');}
function refresh(text,p=fixture()){return engine.refresh(text,p,p.situation?.lines?.providers[0]??null,paths,'2099-10-08T12:00:00Z','https://engine.test',parseYaml,'America/New_York');}

test('initial import maps real API fields, home signs, forecast units, and blank juice',()=>{
  const text=refresh(initial()),fm=metadata(text);
  assert.equal(fm.line,-3.5);assert.equal(fm.total,48.5);assert.equal(fm.price,null);
  assert.equal(fm.over_price,null);assert.equal(fm.engine_game_id,123);assert.equal(fm.home_moneyline,-180);
  assert(text.includes('45%'));assert(text.includes('60 °F'));assert(text.includes('15 mph wind'));
  assert(text.includes('| Home U | 12 | 60 | 24 |'));assert(text.includes('Seconds / play allowed: 27'));
  assert(text.includes('Quarterback questionable. Role: REPORTING'));assert(!text.includes('confirmed out'));
});
test('refresh preserves every manual section, initial quote, and custom multiline properties',()=>{
  let text=refresh(initial());text=text.replace('- Thesis:','- Thesis: MY ORIGINAL CONCLUSION')
    .replace('line: -3.5','line: -4').replace('status: "research"','status: "bet"')
    .replace('---\n','---\ncustom: |\n  multi\n  line\n');
  const p=fixture();p.situation.lines.providers[0].spread=-6;
  const next=refresh(text,p),fm=metadata(next);
  assert.equal(fm.line,-4);assert.equal(fm.engine_line,-6);assert.equal(fm.status,'bet');
  assert(next.includes('MY ORIGINAL CONCLUSION'));assert(next.includes('custom: |\n  multi\n  line'));
  assert(next.includes('cfb:observations-home-offense:start'));assert.equal(engine.block(next,'home-offense').content,'');
});
test('no quote from a different book fills initial fields under the original book',()=>{
  const text=initial().replace('sportsbook: ""','sportsbook: "Bovada"');
  const fm=metadata(refresh(text));assert.equal(fm.line,null);assert.equal(fm.total,null);
  assert.equal(fm.sportsbook,'Bovada');assert.equal(fm.engine_sportsbook,'DraftKings');
});
test('observations deduplicate by stable ID and retain user directions and lifecycle edits',()=>{
  let text=refresh(initial());text=text.replace('|  |  | Quarterback questionable.', '| Important absence |  | Quarterback questionable.')
    .replace('| watch | 2099-10-09 | availability:away:10 |','| retired | when starter returns | availability:away:10 |');
  const next=refresh(text);
  assert.equal((next.match(/availability:away:10/g)||[]).length,1);
  assert(/\| Important absence \| *\| Quarterback questionable\./.test(next));
  assert(next.includes('| retired | when starter returns | availability:away:10 |'));
});
test('older reporting and availability stay linked when absent from latest response',()=>{
  const p=fixture(),old=refresh(initial());p.content={};p.situation.availability=[];
  const next=refresh(old,p);assert(next.includes('https://news.test/a'));assert(next.includes('https://news.test/b'));
});
test('partial endpoint failure retains previous weather, reporting, projection, and latest quote',()=>{
  const old=refresh(initial()),p=fixture();delete p.situation;delete p.preview;delete p.content;p.errors=['situation unavailable'];
  const next=refresh(old,p),fm=metadata(next);assert(next.includes('15 mph wind'));assert(next.includes('Matchup report'));
  assert(next.includes('| Home U | 12 | 60 | 24 |'));assert.equal(fm.engine_line,-3.5);assert.equal(fm.engine_import_status,'partial');
});
test('missing market/forecast remain unknown and zero is preserved',()=>{
  const p=fixture();p.situation.lines.providers[0].spread=0;p.situation.weather={available:false};
  let next=refresh(initial(p),p);assert.equal(metadata(next).line,0);assert(next.includes('no forecast available'));
  p.situation.lines.providers=[];next=refresh(next,p);assert.equal(metadata(next).engine_line,null);
  assert(next.includes('no selected provider quote'));assert(!next.includes('consensus_spread'));
});
test('neutral games omit incorrect home-campus travel and kickoff date uses local timezone',()=>{
  const p=fixture();p.game.neutral_site=1;const next=refresh(initial(p),p);
  assert(!next.includes('Away U travels 500 miles'));assert(next.includes('Neutral site'));
  assert.equal(engine.dateInZone('2099-10-10T01:00:00Z'),'2099-10-09');
});
test('URLs and identity conflicts stop rather than sending notes or merging the wrong game',()=>{
  assert.equal(engine.parseGameInput('https://engine.test/college-football/games/123/','https://engine.test'),123);
  assert.throws(()=>engine.parseGameInput('https://other.test/college-football/games/123/','https://engine.test'),/different engine/);
  assert.throws(()=>engine.baseUrl('http://external.test'),/HTTPS/);assert.equal(engine.baseUrl('http://localhost:5000'),'http://localhost:5000');
  assert.throws(()=>refresh(initial().replace('season: 2099','season: 2098')),/season/);
  assert.throws(()=>refresh(initial().replace('Home U.md','Other U.md').replace('Teams/Home U]]','Teams/Other U]]')),/home team/);
  assert.throws(()=>refresh(refresh(initial()).replace('engine_game_id: 123','engine_game_id: 999')),/another engine game/);
});
test('damaged marker refuses refresh and retrospective data are identified',()=>{
  assert.throws(()=>refresh(refresh(initial()).replace('<!-- cfb:engine-home-offense:end -->','')),/Damaged/);
  const p=fixture();p.game.completed=1;assert(refresh(initial(p),p).includes('Retrospective import'));
});
function runtime(p=fixture()){
  const files=new Map([[`${BASE}/Views/team-page.md`,fs.readFileSync(path.join(ROOT,BASE,'Views/team-page.md'),'utf8')]]);
  const file=p=>files.has(p)?{path:p,basename:p.split('/').at(-1).replace(/\.md$/,'')}:null;
  const prompts=['123','123'];const hooks=[];
  const tp={file:{path:()=>`${BASE}/CFB Dashboard.md`},hooks:{on_all_templates_executed:fn=>hooks.push(fn)},
    system:{prompt:async()=>prompts.shift(),suggester:async(labels,values)=>values[0]},
    obsidian:{parseYaml,Notice:class {},requestUrl:async({url,method})=>{
      assert.equal(method,'GET');const kind=url.split('/').at(-1);
      return {status:200,json:kind==='123'?p.game:kind==='preview'?p.preview:kind==='situation'?p.situation:p.content};}},
    app:{workspace:{openLinkText:()=>{}},vault:{getAbstractFileByPath:file,getMarkdownFiles:()=>[...files.keys()].filter(p=>p.endsWith('.md')).map(file),
      read:async f=>files.get(f.path),createFolder:async p=>files.set(p,null),create:async(p,text)=>{assert(!files.has(p));files.set(p,text);return file(p)},
      process:async(f,fn)=>files.set(f.path,fn(files.get(f.path)))}}};return {tp,files};
}
test('end-to-end Templater run creates/reuses team pages and refreshes one matchup',async()=>{
  const {tp,files}=runtime();const first=await engine.run(tp);assert.equal(metadata(files.get(first)).engine_game_id,123);
  assert.equal([...files.keys()].filter(p=>p.startsWith(`${BASE}/Teams/`)&&p.endsWith('.md')).length,2);
  files.set(first,files.get(first).replace('- Thesis:','- Thesis: KEEP'));
  const second=await engine.run(tp);assert.equal(second,first);assert(files.get(first).includes('- Thesis: KEEP'));
  const snap=await engine.freeze(tp);assert.equal(metadata(files.get(snap)).type,'cfb-pregame-snapshot');
  assert(files.get(snap).includes('- Thesis: KEEP'));assert.equal(metadata(files.get(first)).type,'cfb-matchup');
});
test('snapshot after kickoff and import from active matchup are refused',async()=>{
  const p=fixture();p.game.start_date='2020-10-10T16:00:00Z';const {tp,files}=runtime(p);await engine.run(tp);
  await assert.rejects(engine.freeze(tp),/Kickoff has passed/);
  tp.file.path=()=>`${BASE}/Matchups/active.md`;await assert.rejects(engine.run(tp),/CFB Dashboard/);
});
test('required game failure writes no notes',async()=>{
  const {tp,files}=runtime();tp.obsidian.requestUrl=async()=>({status:503,json:{}});
  await assert.rejects(engine.run(tp),/HTTP 503/);assert.equal(files.size,1);
});
test('unrelated index notes in team/matchup folders do not block import or snapshot',async()=>{
  const {tp,files}=runtime();files.set(`${BASE}/Teams/Index.md`,'# Teams index');
  files.set(`${BASE}/Matchups/Index.md`,'# Matchups index');
  const target=await engine.run(tp);assert.equal(metadata(files.get(target)).type,'cfb-matchup');
  const snapshot=await engine.freeze(tp);assert.equal(metadata(files.get(snapshot)).type,'cfb-pregame-snapshot');
});
test('team queries show authored assessments, isolate side, and link the full archive',async()=>{
  const text=refresh(initial()).replace('> |  |  | Success rate: 45%', '> | Pressure advantage |  | Success rate: 45%');const output=[];const dv={
    current:()=>({file:{path:paths.home},season:2099}),
    pages:query=>query.includes("Observations")?[]:[{...metadata(text),file:{path:`${BASE}/Matchups/game.md`}}],
    view:async()=>{},
    io:{load:async()=>text},date:()=>({toFormat:()=> '2099-10-08'}),
    fileLink:(path,e,label)=>({path,label,toString:()=>`[[${path}]]`}),sectionLink:(path,section,e,label)=>({path,section,label}),
    table:(headers,rows)=>output.push({headers,rows}),paragraph:text=>output.push({text}),header:(level,text)=>output.push({text})};
  await new AsyncFunction('dv','input',viewSource)(dv,{mode:'offense'});
  assert(output[0].rows.length>0);assert.equal(output[0].rows[0][1],metadata(text).away_team);
  assert(output[0].rows.some(row=>String(row[5]).includes('45%')));assert(!JSON.stringify(output).includes('Quarterback questionable'));
  output.length=0;await new AsyncFunction('dv','input',viewSource)(dv,{mode:'games'});
  assert(JSON.stringify(output).includes('full source archive'));assert(!JSON.stringify(output).includes('Matchup report'));
});

const editor=new Function(fs.readFileSync(path.join(ROOT,BASE,'Views/cfb-edit.js'),'utf8'))();
test('rounding affects displays only and publication dates retain no visible clock times',()=>{
  const p=fixture();p.game.advanced_metrics['Home U'].offense_ppa=.123456;
  p.preview.projection.home={drives:12.3456,plays:62.9876,expected_points:28.7654};
  p.situation.weather.latest.temperature=61.789;p.situation.weather.latest.sustained_wind=14.567;
  p.content.reported[0].published_at='2099-10-08T08:12:34Z';
  const text=refresh(initial(p),p),visible=text.replace(/^---[\s\S]*?---/,'').replace(/<!--[\s\S]*?-->/g,'');
  assert(visible.includes('PPA / play: 0.12'));assert(visible.includes('| Home U | 12.3 | 63 | 28.8 |'));
  assert(visible.includes('62 °F'));assert(visible.includes('15 mph wind'));assert(!visible.includes('T08:12:34'));
  assert(!visible.includes('Fetched:'));assert(visible.includes('2099-10-08'));
  assert.equal(metadata(text).engine_market_timestamp,'2099-10-08T00:00:00Z');assert.equal(metadata(text).line,-3.5);
  assert(text.includes('cfb:provenance:'));assert.equal(engine.cleanDisplay(text),text);
});
test('form saves multiline notes with pipes into the right team and preserves unrelated sections',()=>{
  const original=refresh(initial());const values={side:'away',category:'defense',plus:'Coverage | improved',minus:'',evidence:'Film\n[[Note|label]]',carry:'active',review:'2099-10-20'};
  const next=editor.saveRow(original,engine,null,values),rows=editor.entries(next,engine);
  const row=rows.find(r=>r.id==='away-defense');assert(row);assert.equal(row.cells[0],'Coverage | improved');
  assert.equal(row.cells[2],'Film<br>[[Note|label]]');assert.equal(row.cells[3],'active');
  assert.equal(engine.block(next,'home-defense').content,engine.block(original,'home-defense').content);
  const edited=editor.saveRow(next,engine,row,{...values,plus:'Updated',carry:'retired'});
  assert.equal(editor.entries(edited,engine).filter(r=>r.id==='away-defense').length,1);
  assert(edited.includes('| Updated |'));assert(edited.includes('| retired | 2099-10-20 |'));
  assert.throws(()=>editor.saveRow(edited,engine,row,values),/Row changed/);
});
test('form keeps imported evidence and item IDs intact; refresh preserves its assessment',()=>{
  const original=refresh(initial()),row=editor.entries(original,engine).find(r=>r.id==='engine-away-context'&&r.cells[5]==='availability:away:10');
  const next=editor.saveRow(original,engine,row,{plus:'Check starter',minus:'',evidence:'Must not replace source',carry:'active',review:'when starter returns'});
  const result=editor.entries(refresh(next),engine).find(r=>r.cells[5]==='availability:away:10');
  assert.equal(result.cells[0],'Check starter');assert.equal(result.cells[3],'active');assert.equal(result.cells[4],'when starter returns');
  assert(result.cells[2].includes('Quarterback questionable'));assert(!next.includes('Must not replace source'));
});
test('native form exposes full fields, saves changes, locks imported evidence, and cancels',async()=>{
  let modal;const controls=[];
  class Component {
    constructor(kind,label){this.kind=kind;this.label=label;this.inputEl={style:{}};controls.push(this);}
    addOption(){return this}setValue(v){this.value=v;return this}setDisabled(v){this.disabled=v;return this}
    onChange(fn){this.change=fn;return this}setButtonText(v){this.text=v;return this}setCta(){return this}onClick(fn){this.click=fn;return this}
  }
  class Setting {
    setName(v){this.name=v;return this}setDesc(){return this}
    addDropdown(fn){fn(new Component('dropdown',this.name));return this}
    addTextArea(fn){fn(new Component('area',this.name));return this}
    addText(fn){fn(new Component('text',this.name));return this}
    addButton(fn){fn(new Component('button',this.name));return this}
  }
  class Modal {
    constructor(){modal=this;this.contentEl={createEl(){},empty(){}}}
    open(){this.onOpen()}close(){this.onClose()}
  }
  const tp={app:{},obsidian:{Modal,Setting,Notice:class{}}};
  const initial={side:'home',category:'context',plus:'',minus:'',evidence:'Full source text',carry:'watch',review:'',fixed:true};
  let pending=editor.form(tp,initial,true,{home:'Home U',away:'Away U'});
  assert(controls.find(c=>c.label==='Evidence / condition').disabled);
  assert.equal(controls.find(c=>c.label==='Evidence / condition').value,'Full source text');
  controls.find(c=>c.label==='+ Favorable observation').change('Return expected');
  controls.find(c=>c.text==='Save note').click();assert.equal((await pending).plus,'Return expected');
  controls.length=0;pending=editor.form(tp,initial,false,{home:'Home U',away:'Away U'});
  controls.find(c=>c.text==='Cancel').click();assert.equal(await pending,null);
});
const observations=new Function(fs.readFileSync(path.join(ROOT,BASE,'Views/cfb-observations.js'),'utf8'))();
const observationViewSource=fs.readFileSync(path.join(ROOT,BASE,'Views/cfb-observation-view.js'),'utf8');
test('compact comparisons preserve all sources and archive irrelevant or stale headlines',()=>{
  const p=fixture();p.content.reported.push(
    {content_id:20,title:'Home U vs Away U injury report',published_at:'2099-10-08',canonical_url:'https://news.test/current'},
    {content_id:21,title:'Home U vs Away U last season',published_at:'2099-09-01',canonical_url:'https://news.test/old'},
    {content_id:22,title:'Unrelated university go karts',published_at:'2099-10-08',canonical_url:'https://news.test/unrelated'});
  const text=refresh(initial(),p),brief=engine.block(text,'engine-brief').content;
  assert(brief.includes('Home U offense vs. Away U defense'));assert(brief.includes('| PPA / play | — | -0.12 |'));
  assert(brief.includes('4 games · 2099-10-08'));assert(brief.includes('Home U vs Away U injury report'));
  assert(!brief.includes('last season'));assert(!brief.includes('go karts'));
  const reporting=engine.block(text,'engine-reporting').content;assert(reporting.includes('last season'));assert(reporting.includes('go karts'));
  assert(text.includes('> [!abstract]- Full source: reporting'));
  assert.equal(engine.block(refresh(text,p),'engine-reporting').content.split('\n').filter(l=>l.startsWith('|')).length,reporting.split('\n').filter(l=>l.startsWith('|')).length);
  assert.equal((refresh(text,p).match(/cfb:engine-brief:start/g)||[]).length,1);
});
test('organizer preserves authored legacy rows and unknown prose without duplication',async()=>{
  const {tp,files}=runtime();files.set(`${BASE}/Views/cfb-engine.js`,fs.readFileSync(path.join(ROOT,BASE,'Views/cfb-engine.js'),'utf8'));
  const file=`${BASE}/Matchups/legacy.md`;
  const original=initial().replace('| | | | game-only | |','| Protection improved | | Film | active | after next game |').replace('- Thesis:','- Thesis: ORIGINAL');
  files.set(file,original);
  await observations.organizeExisting(tp);
  let notes=[...files.keys()].filter(p=>p.startsWith(`${BASE}/Observations/`)&&p.endsWith('.md'));
  assert.equal(notes.length,1);const props=metadata(files.get(notes[0]));
  assert.equal(props.team,'[[06 Sports Betting/Football/CFB/Teams/Away U]]');assert.equal(props.opponent,'[[06 Sports Betting/Football/CFB/Teams/Home U]]');
  assert.equal(props.carry,'active');assert(files.get(file).includes('ORIGINAL'));assert(engine.block(files.get(file),'away-offense').content.includes('Protection improved'));
  await observations.organizeExisting(tp);
  notes=[...files.keys()].filter(p=>p.startsWith(`${BASE}/Observations/`)&&p.endsWith('.md'));assert.equal(notes.length,1);
});
function atomicUI(tp,onOpen){
  const controls=[];
  class C {constructor(label){this.label=label;this.inputEl={style:{}};controls.push(this)}addOption(){return this}setValue(v){this.value=v;return this}setDisabled(v){this.disabled=v;return this}onChange(f){this.change=f;return this}setButtonText(v){this.text=v;return this}setCta(){return this}onClick(f){this.click=f;return this}}
  class Setting {constructor(){this.settingEl={style:{}};this.controlEl={style:{}}}setName(v){this.name=v;return this}setDesc(){return this}addDropdown(f){f(new C(this.name));return this}addTextArea(f){f(new C(this.name));return this}addText(f){f(new C(this.name));return this}addButton(f){f(new C(this.name));return this}}
  class Modal {constructor(){this.modalEl={style:{}};this.contentEl={createEl(){},empty(){}}}open(){controls.length=0;this.onOpen();onOpen(controls)}close(){this.onClose()}}
  tp.obsidian.Modal=Modal;tp.obsidian.Setting=Setting;
}
test('capture form creates and edits an atomic note, keeps unknown properties/prose and cancels cleanly',async()=>{
  const {tp,files}=runtime();files.set(`${BASE}/Views/cfb-engine.js`,fs.readFileSync(path.join(ROOT,BASE,'Views/cfb-engine.js'),'utf8'));
  const match=`${BASE}/Matchups/game.md`;files.set(match,refresh(initial()));
  atomicUI(tp,c=>{c.find(x=>x.label==='Observation').change('Front seven depth');c.find(x=>x.label==='Evidence / sources / conditions').change('Full evidence\nSecond line');c.find(x=>x.label==='Team').change('home');c.find(x=>x.label==='Carry forward').change('watch');c.find(x=>x.text==='Save observation').click()});
  const target=await observations.open(tp.app,tp.obsidian,{matchupPath:match,category:'defense'});
  const fm=metadata(files.get(target));assert.equal(fm.team,'[[06 Sports Betting/Football/CFB/Teams/Home U]]');assert.equal(fm.opponent,'[[06 Sports Betting/Football/CFB/Teams/Away U]]');assert.equal(fm.category,'defense');assert.equal(fm.matchup,`[[${match.replace(/\.md$/,'')}]]`);
  files.set(target,files.get(target).replace('---\n','---\ncustom: "KEEP"\n')+'\n## Extra section\n\nKEEP PROSE\n');
  atomicUI(tp,c=>{assert(c.find(x=>x.label==='Originating matchup').disabled);c.find(x=>x.label==='Observation').change('Depth confirmed');c.find(x=>x.label==='Follow-up').change('Check next week');c.find(x=>x.text==='Save observation').click()});
  await observations.open(tp.app,tp.obsidian,{observationPath:target});
  assert.equal(metadata(files.get(target)).observation,'Depth confirmed');assert.equal(metadata(files.get(target)).custom,'KEEP');assert(files.get(target).includes('KEEP PROSE'));assert(files.get(target).includes('Full evidence\nSecond line'));
  const before=files.get(target),count=files.size;
  atomicUI(tp,c=>c.find(x=>x.text==='Cancel').click());assert.equal(await observations.open(tp.app,tp.obsidian,{observationPath:target}),undefined);
  assert.equal(files.get(target),before);assert.equal(files.size,count);
});
test('freeze copies full observation content and removes live queries and management grids',async()=>{
  const {tp,files}=runtime();const match=await engine.run(tp);
  const obs=`${BASE}/Observations/insight.md`;
  files.set(obs,observations.serialize(metadata(files.get(match)),{path:match},{side:'away',category:'offense',direction:'positive',observation:'Original thesis',evidence:'Full source evidence',followup:'Check lineup',carry:'active',review:'2099-10-10'},'insight'));
  const snap=await engine.freeze(tp),frozen=files.get(snap);assert(frozen.includes('Original thesis'));assert(frozen.includes('Full source evidence'));assert(frozen.includes('Check lineup'));
  assert(!frozen.includes('await dv.view'));assert(!frozen.includes('![[06 Sports Betting/Football/CFB/Views/matchup-observations.base]]'));
  files.set(obs,files.get(obs).replaceAll('Original thesis','REVISED'));assert.equal(files.get(snap),frozen);
});
test('atomic observation views isolate team, season, category and active status with full text',async()=>{
  const out=[],nodes=[];const records=[
    {type:'cfb-observation',team:paths.home,opponent:paths.away,season:2099,category:'defense',side:'home',matchup:`${BASE}/Matchups/game.md`,observation:'Full untruncated insight',carry:'active',review:'2099-10-01',direction:'positive',file:{path:`${BASE}/Observations/one.md`}},
    {type:'cfb-observation',team:paths.away,season:2099,category:'defense',carry:'active',observation:'OPPONENT INSIGHT',file:{path:'other.md'}},
    {type:'cfb-observation',team:paths.home,season:2098,category:'defense',carry:'active',observation:'OLD SEASON',file:{path:'old.md'}},
    {type:'cfb-observation',team:paths.home,season:2099,category:'offense',carry:'retired',observation:'RETIRED OFFENSE',file:{path:'retired.md'}}];
  const dv={current:()=>({type:'cfb-team',season:2099,file:{path:paths.home}}),pages:()=>records,date:()=>({toFormat:()=> '2099-10-08'}),fileLink:p=>`[[${p}]]`,paragraph:s=>out.push(s),container:{createEl:(_,options)=>{const n={...options,addEventListener(){}};nodes.push(n);return n}}};
  await new AsyncFunction('dv','input',observationViewSource)(dv,{active:true,category:'defense'});
  assert(out.join('\n').includes('Full untruncated insight'));assert(out.join('\n').includes('REVIEW DUE'));assert(!out.join('\n').includes('OPPONENT INSIGHT'));assert(!out.join('\n').includes('OLD SEASON'));assert(!out.join('\n').includes('RETIRED OFFENSE'));assert.equal(nodes.filter(n=>n.text==='Edit').length,1);
});
test('capture from a team page restricts matchups and follows that team across home/away roles',async()=>{
  const {tp,files}=runtime();const one=`${BASE}/Matchups/game1.md`,two=`${BASE}/Matchups/game2.md`;
  files.set(one,refresh(initial()));files.set(two,refresh(initial()).replace('home_team: "[[06 Sports Betting/Football/CFB/Teams/Home U]]"','home_team: "[[06 Sports Betting/Football/CFB/Teams/Away U]]"').replace('away_team: "[[06 Sports Betting/Football/CFB/Teams/Away U]]"','away_team: "[[06 Sports Betting/Football/CFB/Teams/Home U]]"'));
  atomicUI(tp,c=>{assert(c.find(x=>x.label==='Team').disabled);assert.equal(c.find(x=>x.label==='Team').value,'away');c.find(x=>x.label==='Originating matchup').change(one);assert.equal(c.find(x=>x.label==='Team').value,'home');c.find(x=>x.label==='Observation').change('Subject stays Home U');c.find(x=>x.text==='Save observation').click()});
  const target=await observations.open(tp.app,tp.obsidian,{teamPath:paths.home});assert.equal(metadata(files.get(target)).team,'[[06 Sports Betting/Football/CFB/Teams/Home U]]');assert.equal(metadata(files.get(target)).side,'home');
});
test('observation form refuses to overwrite an edit made while the modal was open',async()=>{
  const {tp,files}=runtime();files.set(`${BASE}/Views/cfb-engine.js`,fs.readFileSync(path.join(ROOT,BASE,'Views/cfb-engine.js'),'utf8'));
  const match=`${BASE}/Matchups/game.md`;files.set(match,refresh(initial()));const target=`${BASE}/Observations/one.md`;
  files.set(target,observations.serialize(metadata(files.get(match)),{path:match},{side:'home',category:'context',direction:'neutral',observation:'Check conditions',evidence:'Original',carry:'watch'},'one'));
  atomicUI(tp,c=>{files.set(target,files.get(target)+'\nEXTERNAL EDIT\n');c.find(x=>x.label==='Observation').change('Do not overwrite');c.find(x=>x.text==='Save observation').click()});
  await assert.rejects(observations.open(tp.app,tp.obsidian,{observationPath:target}),/changed while editing/);assert(files.get(target).includes('EXTERNAL EDIT'));assert.equal(metadata(files.get(target)).observation,'Check conditions');
});


test('workflow upgrades preserve prose, editorial fields, and repeated refreshes',()=>{
  const raw=initial();
  const authored=engine.patchProperties(raw,{article_status:'draft',central_argument:'Pressure matters',custom_property:'Keep'},parseYaml).replace('- Thesis:','- Thesis: My original thesis');
  const upgraded=engine.organize(authored,parseYaml);
  assert.equal(metadata(upgraded).article_status,'draft');assert.equal(metadata(upgraded).central_argument,'Pressure matters');
  assert.ok(upgraded.includes('- Thesis: My original thesis'));assert.equal(metadata(upgraded).custom_property,'Keep');
  assert.ok(upgraded.includes('Bet only if'));assert.equal(engine.organize(upgraded,parseYaml),upgraded);
});
test('action fields preserve binary zero probability and reject invalid inputs',()=>{
  const helper=new Function(fs.readFileSync(path.join(ROOT,BASE,'Views/cfb-observations.js'),'utf8'))();
  assert.equal(helper.actionFields({probability:'0',publishable:'true'}).probability,0);
  assert.equal(helper.actionFields({probability:'',publishable:'false'}).probability,null);
  assert.equal(helper.actionFields({publishable:'false'}).publishable,false);
  for(const probability of [-1,101,'unknown'])assert.throws(()=>helper.actionFields({probability}),/Probability/);
  assert.throws(()=>helper.actionFields({prediction_result:'won'}),/Invalid prediction/);
});
