"""Generate static/nfl_neutral.css: the neutral-dark retint of the older NFL component styles.

`nfl.css` / `nfl_components.css` paint cards, strips and tables in a blue-gray palette
(#101b23, #14242e, #2b3e4b, ...). The newer `ui_kit.css` kit uses neutral dark surfaces.
Rather than edit ~1,000 literals in the legacy files (`tests/test_nfl_theme.py` guards
them), this script emits scoped overrides that recolor only the *background / border /
shadow* declarations that use a dark, low-chroma, blue-leaning hex, and nothing else:
text colors, team colors, saturated accents and layout are left alone.

Usage (from the project root):  python scripts/build_nfl_neutral_css.py
Add a page's body class to SCOPES to bring another page onto the same surfaces.
"""

from __future__ import annotations

import re
from pathlib import Path

SOURCES = ("static/nfl.css", "static/nfl_components.css")
OUTPUT = Path("static/nfl_neutral.css")
SCOPES = ("nfl-matchup-page", "nfl-team-page", "nfl-player-page")
TOKENS = {"--panel": "#17181c", "--surface": "#1a1c20", "--line": "#2c3038"}
PROPERTY = re.compile(r"^(background(-color|-image)?|border(-[a-z]+)*|box-shadow|outline)$")
HEX = re.compile(r"#([0-9a-fA-F]{6})\b")


def retint(match: re.Match) -> str:
    red, green, blue = (int(match.group(1)[i:i + 2], 16) for i in (0, 2, 4))
    dark = max(red, green, blue) <= 0x62
    quiet = max(red, green, blue) - min(red, green, blue) <= 48
    bluish = blue >= red
    if not (dark and quiet and bluish):
        return match.group(0)
    mean = round((red + green + blue) / 3)
    return "#{:02x}{:02x}{:02x}".format(max(mean - 1, 0), mean, min(mean + 3, 255))


def split_declarations(body: str) -> list[str]:
    parts, depth, quote, current = [], 0, "", []
    for char in body:
        if quote:
            current.append(char)
            if char == quote:
                quote = ""
            continue
        if char in "\"'":
            quote = char
        elif char == "(":
            depth += 1
        elif char == ")":
            depth -= 1
        elif char == ";" and depth == 0:
            parts.append("".join(current))
            current = []
            continue
        current.append(char)
    if "".join(current).strip():
        parts.append("".join(current))
    return parts


def walk(css: str):
    """Yield ('rule', selector, body) or ('media', prelude, inner_css)."""
    index, length = 0, len(css)
    while index < length:
        open_at = css.find("{", index)
        if open_at == -1:
            break
        prelude = css[index:open_at].strip()
        depth, cursor = 1, open_at + 1
        while cursor < length and depth:
            depth += {"{": 1, "}": -1}.get(css[cursor], 0)
            cursor += 1
        inner = css[open_at + 1:cursor - 1]
        yield ("media" if prelude.startswith("@media") else "rule"), prelude, inner
        index = cursor


def scoped(selector: str, scope: str) -> str:
    selector = selector.strip()
    if selector.startswith((".%s" % scope, "body.%s" % scope)):
        return selector
    if selector in {"html", ":root"} or selector.startswith(("html ", ":root")):
        return ""
    if selector == "body":
        return f"body.{scope}"
    return f".{scope} {selector}"


def overrides(css: str, scopes: tuple[str, ...]) -> list[str]:
    output: list[str] = []
    for kind, prelude, inner in walk(css):
        if kind == "media":
            nested = overrides(inner, scopes)
            if nested:
                output.append(f"{prelude}{{{''.join(nested)}}}")
            continue
        if prelude.startswith("@"):
            continue
        changed = []
        for declaration in split_declarations(inner):
            if ":" not in declaration:
                continue
            name, value = declaration.split(":", 1)
            if not PROPERTY.match(name.strip()):
                continue
            recolored = HEX.sub(retint, value)
            if recolored != value:
                changed.append(f"{name.strip()}:{recolored.strip()}")
        if not changed:
            continue
        selectors = []
        for selector in prelude.split(","):
            for scope in scopes:
                target = scoped(selector, scope)
                if target:
                    selectors.append(target)
        if selectors:
            output.append(f"{','.join(dict.fromkeys(selectors))}{{{';'.join(changed)}}}")
    return output


def build() -> str:
    blocks = []
    for source in SOURCES:
        css = re.sub(r"/\*.*?\*/", "", Path(source).read_text(encoding="utf-8"), flags=re.S)
        blocks.extend(overrides(css, SCOPES))
    tokens = ";".join(f"{name}:{value}" for name, value in TOKENS.items())
    header = ("/* GENERATED by scripts/build_nfl_neutral_css.py: do not edit by hand.\n"
              "   Neutral-dark surfaces for the legacy NFL component styles; see the script docstring. */\n")
    root = ",".join(f".{scope}" for scope in SCOPES)
    return header + f"{root}{{{tokens}}}\n" + "\n".join(blocks) + "\n"


def main() -> None:
    OUTPUT.write_text(build(), encoding="utf-8")
    print(f"wrote {OUTPUT}")


if __name__ == "__main__":
    main()
